### ISSUE TITLE
StandUp meeting 13/11/2019

### ISSUE THREAD

**Issue by mesielepush** [leonmezu1/Microverse-Capstone-Social-Network#1]
Review of last five commits by standup team morning meeting.

1. Could use more efficient hierarchies.
2. Media Queries goes at the bottom.
3. Could use css pre-processor more efficiently.

**Comment by men32z** [comment]
1. Could use more efficient hierarchies.
SCSS preprocessor allows you to do some nice things like this 

```
.bottom-card {
  .....
  span {
	....
  }
  p {
	...
  }
}
```
instead of this

```
.bottom-card {
  ....
}
.bottom-card span {
 ....
}

.bottom-card p {
  .....
}
```

**Comment by leonmezu1** [comment]
Thanks guys! 
I'm going to adjust the project and do the corrections.

**Comment by leonmezu1** [comment]
Closed the issue by mistake
